#!/usr/bin/env python
# coding: utf-8

# # Capstone Project of 1st Week
# 

# Inserting Package and Printing Statement

# In[1]:


import pandas as pd
import numpy as np


# In[2]:


print("Hello Capstone Project Course!")

# In[ ]:
